blank_issues_enabled: false
contact_links:
  - name: Telegram 频道
    url: https://t.me/moviepilot_channel
    about: 更新日志
  - name: Telegram 交流群
    url: https://t.me/moviepilot_official
    about: 交流互助
